### ISSUE TITLE
help me, im brainlet

### ISSUE THREAD

**Issue by 3cbb53c73415ba373448c11dacc69b05** [NellielProject/Nelliel#2]
Warning: md5_file(/home/vol15_6/epizy.com/epiz_22912243/17ch.ml/htdocs/board_files/languages/locale/pt_BR/LC_MESSAGES/nelliel.po): failed to open stream: No such file or directory in /home/vol15_6/epizy.com/epiz_22912243/17ch.ml/htdocs/board_files/include/Language/Language.php on line 30

Fatal error: Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'epiz_22912243_post.nelliel_site_config' doesn't exist in /home/vol15_6/epizy.com/epiz_22912243/17ch.ml/htdocs/board_files/include/classes/NellielPDO.php:116 Stack trace: #0 /home/vol15_6/epizy.com/epiz_22912243/17ch.ml/htdocs/board_files/include/classes/NellielPDO.php(116): PDO->query('SELECT * FROM "...') #1 /home/vol15_6/epizy.com/epiz_22912243/17ch.ml/htdocs/board_files/include/classes/ParametersAndData.php(52): Nelliel\NellielPDO->executeFetchAll('SELECT * FROM "...', 2) #2 /home/vol15_6/epizy.com/epiz_22912243/17ch.ml/htdocs/board_files/include/output/header.php(146): Nelliel\ParametersAndData->siteSettings('home_page') #3 /home/vol15_6/epizy.com/epiz_22912243/17ch.ml/htdocs/board_files/include/output/derp.php(14): nel_render_general_header(Object(NellielTemplates\RenderCore)) #4 /home/vol15_6/epizy.com/epiz_22912243/17ch.ml/htdocs/board_files/include/derp.php(30): nel_render_derp(Array, NULL) #5 /home/vol15_6/epizy.com/epi in /home/vol15_6/epizy.com/epiz_22912243/17ch.ml/htdocs/board_files/include/classes/NellielPDO.php on line 116

**Comment by OtakuMegane** [comment]
What were you doing when this error came up? Was it during the initial install?

**Comment by 3cbb53c73415ba373448c11dacc69b05** [comment]
yeah

**Comment by 3cbb53c73415ba373448c11dacc69b05** [comment]
when i start de imgboard.php

**Comment by OtakuMegane** [comment]
Ok, it looks like there's something wrong during setup but the error page tried to access a table that hasn't been created yet. Made a fix for that, so download [ParametersAndData.php](https://raw.githubusercontent.com/NellielProject/Nelliel/master/board_files/include/classes/ParametersAndData.php) and replace the existing copy in `board_files/include/classes/`

Then run imgboard.php and it should display the error correctly.
