### ISSUE TITLE
oops

### ISSUE THREAD

**Issue by Meido44** [NellielProject/Nelliel#3]
Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes. in /home1/goodimg/public_html/board/board_files/include/Setup/SQLHelpers.php:129 Stack trace: #0 /home1/goodimg/public_html/board/board_files/include/Setup/SQLHelpers.php(129): PDO->query('\n CREATE...') #1 /home1/goodimg/public_html/board/board_files/include/Setup/TableCaptcha.php(45): Nelliel\Setup\SQLHelpers->createTableQuery('\n CREATE...', 'nelliel_captcha') #2 /home1/goodimg/public_html/board/board_files/include/Setup/TableCaptcha.php(30): Nelliel\Setup\TableCaptcha->createTable() #3 /home1/goodimg/public_html/board/board_files/include/Setup/Setup.php(120): Nelliel\Setup\TableCaptcha->setup() #4 /home1/goodimg/public_html/board/board_files/include/Setup/Setup.php(31): Nelliel\Setup\Setup->createCoreTables() #5 /home1/goodimg/public_html/board/imgboard.php(47): Nelliel\Setup\Setup->install() #6 {main} thrown in /home1/goodimg/public_html/board/board_files/include/Setup/SQLHelpers.php on line 129

**Comment by OtakuMegane** [comment]
That was caused by a MySQL/MariaDB limitation I missed. I've updated `board_files/include/Setup/TableCaptcha.php` with a fix that should avoid the problem.

**Comment by Meido44** [comment]
Thank you! The installation works fine now but when I try to create a new board this comes up:

`Fatal error: Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'goodimg_img._config' doesn't exist in /home1/goodimg/public_html/test/board_files/include/classes/NellielPDO.php:205 Stack trace: #0 /home1/goodimg/public_html/test/board_files/include/classes/NellielPDO.php(205): PDO->query('SELECT * FROM "...') #1 /home1/goodimg/public_html/test/board_files/include/classes/DomainBoard.php(92): Nelliel\NellielPDO->executeFetchAll('SELECT * FROM "...', 2) #2 /home1/goodimg/public_html/test/board_files/include/classes/DomainBoard.php(39): Nelliel\DomainBoard->loadSettingsFromDatabase() #3 /home1/goodimg/public_html/test/board_files/include/classes/Domain.php(62): Nelliel\DomainBoard->loadSettings() #4 /home1/goodimg/public_html/test/board_files/include/classes/Domain.php(112): Nelliel\Domain->setting('locale') #5 /home1/goodimg/public_html/test/board_files/include/classes/DomainBoard.php(20): Nelliel\Domain->locale() #6 /home1/goodimg/public_html/test/board_files/include/Admin/AdminBoards.php(76) in /home1/goodimg/public_html/test/board_files/include/classes/NellielPDO.php on line 205`

**Comment by OtakuMegane** [comment]
Fixed the board creation process, there were several issues that snuck in there.

`board_files/include/Setup/Setup.php` and `board_files/include/Admin/AdminBoards.php` have been updated.
