### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by hawkoon** [NellielProject/Nelliel#5]
The installation page says:
> DB engine ok.
> Main directory is writable.
> The core directory is writable.
> The configutation directory is writable.
> Peppers file already present.

However nothing happens. The Apache logs say:
`PHP Fatal error:  Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'VARCHAR(255) NOT NULL PRIMARY KEY,\n            text            VARCHAR(255) NOT ' at line 2 in /var/www/html/nelliel_core/include/Setup/TableHandler.php:163\nStack trace:\n#0 /var/www/html/nelliel_core/include/Setup/TableHandler.php(163): PDO->query('\\n        CREATE...')\n#1 /var/www/html/nelliel_core/include/Setup/TableHandler.php(27): Nelliel\\Setup\\TableHandler->createTableQuery('\\n        CREATE...', 'nelliel_captcha')\n#2 /var/www/html/nelliel_core/include/Setup/Setup.php(167): Nelliel\\Setup\\TableHandler->createTable()\n#3 /var/www/html/nelliel_core/include/Setup/Setup.php(47): Nelliel\\Setup\\Setup->createCoreTables()\n#4 /var/www/html/nelliel_core/include/initializations.php(164): Nelliel\\Setup\\Setup->install()\n#5 /var/www/html/imgboard.php(12): require_once('/var/www/html/n...')\n#6 {main}\n  thrown in /var/www/html/nelliel_core/include/Setup/TableHandler.php on line 163`

I've installed all the necessary dependencies and am using PHP 7.2 with MariaDB 10.4 on CentOS 7.

**Comment by OtakuMegane** [comment]
There was a naming conflict on some database columns. Got that fixed now.

Files updated:
`nelliel_core/include/Account/Login.php`
`nelliel_core/include/Account/Register.php`
`nelliel_core/include/Setup/TableCaptcha.php`
`nelliel_core/include/Setup/TableLoginAttempts.php`
`nelliel_core/include/classes/CAPTCHA.php`
