### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by hawkoon** [NellielProject/Nelliel#6]
Using MariaDB. After refreshing the installation page pic related shows but nothing happens.
![this](https://user-images.githubusercontent.com/54553501/82598140-73eed900-9baa-11ea-90cf-981704f2542f.png)

Apache logs say:

> PHP Notice:  Undefined variable: core_path in /var/www/html/imgboard.php on line 8
> PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1005 Can't create table `db`.`nelliel_overboard` (errno: 121 "Duplicate key on write or update") in /var/www/html/nelliel_core/include/Setup/TableHandler.php:168\nStack trace:\n#0 /var/www/html/nelliel_core/include/Setup/TableHandler.php(168): PDO->query('\\n        CREATE...')\n#1 /var/www/html/nelliel_core/include/Setup/TableHandler.php(27): Nelliel\\Setup\\TableHandler->createTableQuery('\\n        CREATE...', 'nelliel_overboa...')\n#2 /var/www/html/nelliel_core/include/Setup/Setup.php(189): Nelliel\\Setup\\TableHandler->createTable(Array)\n#3 /var/www/html/nelliel_core/include/Setup/Setup.php(47): Nelliel\\Setup\\Setup->createCoreTables()\n#4 /var/www/html/nelliel_core/include/initializations.php(170): Nelliel\\Setup\\Setup->install()\n#5 /var/www/html/imgboard.php(16): require_once('/var/www/html/n...')\n#6 {main}\n  thrown in /var/www/html/nelliel_core/include/Setup/TableHandler.php on line 168

**Comment by OtakuMegane** [comment]
Took some time to look over and debug the install process and try it on all 4 types. Things should work the whole way now. Remove any tables from the database that already got created and update, then give it another try.

**Comment by githubfag** [comment]
I get this:

`Warning: Use of undefined constant LC_MESSAGES - assumed 'LC_MESSAGES' (this will throw an Error in a future version of PHP) in D:\Programme\xampp\htdocs\nelliel_core\include\initializations.php on line 160

Fatal error: Uncaught TypeError: Argument 3 passed to Nelliel\Language\Language::loadLanguage() must be of the type int, string given, called in D:\Programme\xampp\htdocs\nelliel_core\include\initializations.php on line 160 and defined in D:\Programme\xampp\htdocs\nelliel_core\include\Language\Language.php:39 Stack trace: #0 D:\Programme\xampp\htdocs\nelliel_core\include\initializations.php(160): Nelliel\Language\Language->loadLanguage('en_US', 'nelliel', 'LC_MESSAGES') #1 D:\Programme\xampp\htdocs\imgboard.php(23): require_once('D:\\Programme\\xa...') #2 {main} thrown in D:\Programme\xampp\htdocs\nelliel_core\include\Language\Language.php on line 39`

**Comment by OtakuMegane** [comment]
Happens if PHP isn't compiled with libintl. Added a fix to handle that case.

**Comment by githubfag** [comment]
Now I get this:

Warning: Use of undefined constant LC_MESSAGES - assumed 'LC_MESSAGES' (this will throw an Error in a future version of PHP) in D:\Programme\xampp\htdocs\nelliel_core\include\initializations.php on line 160

Fatal error: Uncaught TypeError: Argument 3 passed to Nelliel\Language\Language::loadLanguage() must be of the type int, string given, called in D:\Programme\xampp\htdocs\nelliel_core\include\initializations.php on line 160 and defined in D:\Programme\xampp\htdocs\nelliel_core\include\Language\Language.php:39 Stack trace: #0 D:\Programme\xampp\htdocs\nelliel_core\include\initializations.php(160): Nelliel\Language\Language->loadLanguage('en_US', 'nelliel', 'LC_MESSAGES') #1 D:\Programme\xampp\htdocs\imgboard.php(23): require_once('D:\\Programme\\xa...') #2 {main} thrown in D:\Programme\xampp\htdocs\nelliel_core\include\Language\Language.php on line 39
